language: scala
scala: 2.11.7
jdk: oraclejdk8
install: ./gradlew check
script: ./gradlew test jar
notifications:
  slack: datamountaineers:gpg5e7VabFjAT1gQZqwxgsqP
after_success:
  - bash <(curl -s https://codecov.io/bash)

